### ISSUE TITLE
Sensor dukker ikke op i Entities

### ISSUE THREAD

**Issue by Dinnsen** [MaximusClavius/Solmoller-Spotprice-Sensor#1]
Hejsa,

Jeg kan ikke få denne sensor til at fungere, den dukker ikke op i Entities. 

Jeg har både en Carnot og Grønne Elforbrug i Configuration.yaml hvor Carnot virker uden problemer. 

Har du en ide om hvorfor? 

På forhånd tak 
Christian 

  - platform: rest
    resource: https://whale-app-dquqw.ondigitalocean.app/openapi/get_predict
    name: elprognose_carnotdk
    scan_interval: 3600
    headers:
      Accept: application/json
      apikey: !secret carnotdk_token
      username: !secret carnotdk_username
    params:
      daysahead: 7
      energysource: spotprice
      region: dk1
    json_attributes:
      - predictions
    value_template: "{% if value_json is not none %}OK {{value_json.predictions[0].addedtime}}{% else %}Unavailable{% endif %}"

  - platform: command_line
    name: Groennere_prognose_DK1
    command: "curl -s https://raw.githubusercontent.com/solmoller/Spotprisprognose/main/prognose.json"
    scan_interval:
      hours: 2
    command_timeout: 30
    value_template: '{% if value_json is not none %}OK {{value_json["Forecast created"]}}{% else %}Unavailable{% endif %}'
    json_attributes:
      - DK1

**Comment by MaximusClavius** [comment]
Forklaring: Grunden til grønnere Elforbrug ikke kommer frem er at "mine" eksemplerne bruger deres egen "comnand_line"-fil, og ikke findes i configuration.yaml. 

Med dit udgangspunkt skal du starte således i configuration.yaml:
command_line:
  - sensor:
      name: Groennere_prognose_DK1
      command: "curl -s https://raw.githubusercontent.com/solmoller/Spotprisprognose/main/prognose.json"
      osv.
      
/Peer

**Comment by Dinnsen** [comment]
Tak 🙏 Det var præcis hvad der skulle til!
